### ISSUE TITLE
Supported passwords

### ISSUE THREAD

**Issue by cypherpunk1984** [ScavengerBot/ScavengerBot#1]
Hi there guys.

I have created an account with a password provided by my Keepass generator. 64 characters, Upper case, Lower case, Numbers, Minus (-), Underline (_), and Special characters (!,$,%, etc). After creating the account, I can't login, I tried creating another account with a simpler password, 20 characters, upper case, lower case and numbers, and it worked w/o problems.
You should warn what kind of passwords are supported, or upgrade the login system to support more complex ones.

Thanks.

**Comment by Crypto2legit** [comment]
This will be addressed during open beta.

**Comment by bigcountry-scav** [comment]
This has been resolved to provide an error message on the special characters that were known to create a failure.
