### ISSUE TITLE
Send out weekly invoice email

### ISSUE THREAD

**Issue by smoochy** [ScavengerBot/ScavengerBot#11]
Heya. 
A lot of people are concerned if they should have received the invoice email or not. Even if they have not reached the PnL limit yet.  So they come to the discord and ask. What is a good thing, but means more work for support staff. 
Would it be possible to send out an email every week, no matter if the PnL was reached or not, so people can be sure that the Bot wouldn't stop working two days later?

**Comment by Crypto2legit** [comment]
Thank you for that input we are working on invoicing currently. We will update the status and operations of the invoicing as we move along.

**Comment by bigcountry-scav** [comment]
This is now the standard in version 2.
