### ISSUE TITLE
Trailing

### ISSUE THREAD

**Issue by Fransenson** [ScavengerBot/ScavengerBot#12]
I’d like to see an option to not have a fixed take profit order but rather a trailing mechanic that follows the price and starts to act as the price direction changes.

**Comment by Crypto2legit** [comment]
Thank you for that input and yes we are working out different strategies options or "addons" to the current one as a selection. We will announce when we get further along.

**Comment by mkarulin** [comment]
Trailing profit would be awesome, when it works :)
There will be a lot of failed orders though, due to slippage and post-only.

**Comment by Crypto2legit** [comment]
It actually should be fine with longer time frames. We have tested this
manually many times.
