### ISSUE TITLE
Detailed Billing

### ISSUE THREAD

**Issue by abunsanctuary** [ScavengerBot/ScavengerBot#13]
Been using Scavenger for the past 10 days  and loving it. Yesterday I received the first invoice for the 15% (paid). Would it be possible in the future to have more detailed information regarding the invoiced amount so we can match with our records. (the period, total profit, etc) thank you

**Comment by Crypto2legit** [comment]
Thank you for your input we are currently working out all the details for invoicing. I have added your request to our ideas log.

**Comment by jadiesel** [comment]
Just to add into the ideas log: An invoice should be generated regardless of the final amount owed... When doing a prepay you currently just see your account balance drop, without seeing an invoice for what your balance was applied to... Needs that simple 'Amount billed', 'Amount Paid', 'Amount Due', even when the amount due = 0...

**Comment by bigcountry-scav** [comment]
This is now included in version 2 release.
