### ISSUE TITLE
Stop loss option & pump/dump protection

### ISSUE THREAD

**Issue by coinnodenl** [ScavengerBot/ScavengerBot#14]
Guys : Please change the text "The world’s most reliable market making trading bot for cryptocurrency." One must not tell lies (i mean : you dont know all bots world wide so you cannot state this).

Got two things for you guys;
1) A sliding button at web interface that gives you the possibility to setup a stop loss.
2) A system protection agains pump/dumps, so it doesnt trade in this annoyings pump/dumps since its way to much risk, you keep more balance so lower change of liq.

**Comment by Crypto2legit** [comment]
Thank you for your suggestions

**Comment by zhelfer0306** [comment]
This times a million. 

There needs to be a high level risk management tool that sets market stop losses as a final safety net. If people know their balance is 99% safe from a pump/dump liquidation, they will undoubtedly pour more money onto the platform. 

Edit:

Just to be more specific, an easy way to implement this would be to simply open a stop order for x contracts when x contracts are bought at a price determined by risk reward ratio. This will solve pump/dump issue. 

Also a way to limit max position size would be fantastic.

**Comment by Crypto2legit** [comment]
As we have stated this has always been a community bot and we never had any funding or upfront costs when we began. The stop loss function is almost done. We had to rewrite alot of the code and make our own API to accommodate all the needed changes for the future. Thanks for the support and we look forward to more input from everyone.

**Comment by bigcountry-scav** [comment]
We now offer trailing stop as well as max position. Market change protection has always been a way to protect from pump and dumps to some degree.
