### ISSUE TITLE
Stoploss MUST be implemented

### ISSUE THREAD

**Issue by Zombato** [ScavengerBot/ScavengerBot#15]
I guess November 14th bloodbath showed, that the roadmap must be changed and the first feature you have to implement is the custom stop loss order (which user can control, setting the percentage of the balance he can afford to loose).

Too many were liqudated today, so this is written in blood.

**Comment by Crypto2legit** [comment]
Like any automated program people need to watch and monitor there investment. This is a community project and we are working on making this better for newer users or people that dont understand how to trade! Thank you for your input and for the record all the team has equally felt the hurdles along the way. We are all in this together.
