### ISSUE TITLE
SOM mode or Autostop bot on 5% drops

### ISSUE THREAD

**Issue by Draztik99** [ScavengerBot/ScavengerBot#16]
My suggestion I mentioned earlier is to create a SOM mode if it reaches a certain liquidation amount or an AutoStop feature on the bot to stop buying at a specific liquidation, for when it goes up or down say more than 5%-10%.

The autostop feature could be set to a specify a specific liquidation to stop buying at like 4300 or 4600. This will allow the market to settle before trading again and or as well allow the user to add more BTC funds to lower their liquidation before restarting the bot again.

**Comment by bigcountry-scav** [comment]
This is already baked in with market change protection.
