### ISSUE TITLE
Invoice payment pr. pair

### ISSUE THREAD

**Issue by tes724** [ScavengerBot/ScavengerBot#17]
I ran into a problem... I use the same account for all trades. Both bot and manual trades.
I would like to see an option in the dashboard to pick a BOT trading pair and then the invoice would only count towards that BOT trading pair. I would like to be able to trade other pairs manually on the side to gain more gains and profit to the bot.

Why not make a 3rd account then? Well i dont have the balance to to so... This is my option to get up to recommended balance and still use the BOT while i sleep. 

As i understand right now, the invoice i calculated for all profit on XBT, but in the future other pairs will be added to the BOT and i wont be able to trade on the side... Please make the option, where you will only get invoice for your traded pair by the BOT.

Thank you

**Comment by bigcountry-scav** [comment]
This isnt an issue as the bot only charges based on what is done on the pair it is configured for already it does not care about other pairs.
