### ISSUE TITLE
Strategy suggestion

### ISSUE THREAD

**Issue by drubsa** [ScavengerBot/ScavengerBot#18]
Hi, I have worked some ideas to mitigate the risk, these numbers are for demonstration purposes.

If (current price - liquidation price [GAP]) <= (current price * 0.33) 
     10 minutes buy timeout after each buy

If (current price - liquidation price) <= (current price * 0.2) 
     stop buying

If (current price - liquidation price) <= (current price * 0.1) 
     get out of position immediately

It's pretty basic stuff, but I would sleep better at night with measure like that implemented

**Comment by bigcountry-scav** [comment]
Thanks for the suggestion.
