### ISSUE TITLE
Possible Buy Strategy

### ISSUE THREAD

**Issue by NoSKii** [ScavengerBot/ScavengerBot#20]
Hey guys,
First of all I'd like to say awesome work with the bot. Loving how it's working right now and the fact that we can hedge both sides of bitcoins crazy movements. 

I wanted to submit a different potential buy strategy, not sure if it's something you're considering or already looked at.

So at the moment the bot is buying very close to the market price. One limit order at a time, just below/above the price based on longing/shorting.

What if instead the bot sets limit buys at multiple prices x% away from the mark price. You could even have say 50 limit buys ranging from 0.1-5% away and so on. So instead of buying like it is now, and having the issue of lots of buys when the price is not moving, you would have buys set at certain prices. (I'm aware the channel implementation has fixed this issue too!)

If not too risky you could look also look at increasing the contract buys the further away you go.

Why not have buys set up even up to 10% away to at least catch some of the major price action while its moving. There is no limit to how many limit buy orders we place so why not prepare ourselves for these big moves. 

You could have the exit price the same as it is now, and once the price moves back in your favour and the order closes cancel all the limit buys. 

I'm not sure if this sort of strategy is something you guys have already considered, and even tho we would be less price neutral, I think by hedging both ways we are giving ourselves the best chance to counter these big moves and make a profit. We are still "Market makers" buy having limit orders set up right!? :) 

Happy to discuss further if it's something you guys are interested in

Thanks for reading!
NoSKi 
Dedicated Gnome Pro User and Scavenger Bot Advocate

**Comment by mmarkplaatstv** [comment]
I do that manually sometimes to catch some wicks that will make a greater change in the average position price. Usually one or two is enough to catch such wicks. Or I amend the orders that ScavengerBot places, however it sometimes cancels them and places them back.
Same goes for opening a new position, which is much faster manually than waiting for the bot.

**Comment by bigcountry-scav** [comment]
Thanks for the suggestion.
