### ISSUE TITLE
Posting of back test results for trade strats

### ISSUE THREAD

**Issue by cryptomonst3r** [ScavengerBot/ScavengerBot#21]
It would be nice to see what kind of backtesting is being done, and the methodology behind it. Results from Monte Carlo simulations, equity curve comparisons, and % risk of ruin stats would be nice as well. They should be updated when tweaks to the algo are made as well.

There needs to be more evidence that the risk/reward is worth our whole balance being exposed.

**Comment by bigcountry-scav** [comment]
Thanks for the suggestion.
