### ISSUE TITLE
Postion Close Order Update

### ISSUE THREAD

**Issue by droolingtaz** [ScavengerBot/ScavengerBot#23]
When XBT is added to a position, the close position order is not updated to the new position size until another position increase order is created.  If the position increase order is not placed the close position order is left with an incorrect size and would not completely close a position.

**Comment by droolingtaz** [comment]
![image](https://user-images.githubusercontent.com/2859049/48799978-7121d800-ecd6-11e8-9d21-8054c2bc3594.png)

**Comment by bigcountry-scav** [comment]
This is handled now outside of the order engine in a special position handler in new release.
