### ISSUE TITLE
Strategy: place multiple orders on quick wicks

### ISSUE THREAD

**Issue by Shutiri** [ScavengerBot/ScavengerBot#26]
Example with short.

**Summary:**
The idea is to place quick increasing orders on potential high wicks, and cancel them if the wick doesn't happen. This way, we could increase the exit price by bigger steps on the way up (as opposed to place orders only on steady channels).

**Rationale:**  (copying from the Discord conversation about it)
The order price goes up based on the price of the trades done above the order price.
As far as I understand, it goes up as an average between order(factor of size) and trade(factor of order). 

If this is the case, SB could place multiple orders WAY above current price so these orders are fulfilled on the crazy quick wicks, thus rising the order price a lot with every order. 

Why not put orders on high wicks, so order price goes higher on every trade?

I'm suggesting that we put orders on high wicks.
For example, price is 4000, put an order at 4020, 4 at 4030, 10 at 4040, 20 at 4050
And cancel if price reaches (and stays) at 4010 for example.
Place orders again on high wicks and so on.
If we place 20 orders at 4050 when price is 4000, this would make our exit price increase by a lot.

It wouldn't work with manual trades, because it's really fast
It would respond to quick wicks, so only a bot could do something like this.

2Legit can you give example on when , and how to decide on wicks ? Time frame?

**Comment by Crypto2legit** [comment]
We have now moved into version 2 and will put this in the requests area.
