### ISSUE TITLE
Multiple orders at the same price

### ISSUE THREAD

**Issue by mmarkplaatstv** [ScavengerBot/ScavengerBot#27]
Currently the bot doesn't care about your position price and keeps dropping buy/sell orders in, even if they're at the exact same value as the earlier ones. If the difference between the position and the current price is too low it should halt instead of just increasing the position at the same price.
Because that will only make it more difficult to DCA when the price moves away.

For example:
XBTUSD | -16 | 4113.0 | -16 |   | 4113.0 | Limit | Filled | Dec 2, 2018, 11:26:21 PM
XBTUSD | -16 | 4111.5 | -16 |   | 4111.5 | Limit | Filled | Dec 2, 2018, 11:25:18 PM
XBTUSD | -16 | 4111.5 | -16 |   | 4111.5 | Limit | Filled | Dec 2, 2018, 11:24:14 PM
XBTUSD | -16 | Market | -16 |   | 4111.5 | Market | Filled | Dec 2, 2018, 11:22:49 PM

At that moment there was only a 16 contract short position open at 4111.5, which is trippled in size without the price having gone up. For this example I had opened a brand new position with that market order.
If the position is far enough away from the current price then keeping a DCA going makes perfect sense, but not in this case.

Earlier today I also noticed a 1 hour period with only a 0,5% range. And this time ScavengerBot also just kept increasing position around the center of that range.

**Comment by Crypto2legit** [comment]
We have changed this to have a channel protection but some people like to build a position. We may have to add an option to choose to build position regardless of price movement. Thank you for getting this on here for us to review further.
