### ISSUE TITLE
Funding Strategy 

### ISSUE THREAD

**Issue by NoSKii** [ScavengerBot/ScavengerBot#30]
After testing the funding pro-script I think scavenger would really benefit from using this strategy.

So instead of running a long and short bot, you would have just one that would switch depending on which side is being paid funding. This would be especially beneficial considering the bot can hold positions for a long time. 

In addition, as it's only one bot, people would be able to have a bigger balance in there and thus be less likely to get liquidated.

Also, adding a leverage of say 5-10 would increase the funding payout which could be a more viable strategy.

Just a thought!

Thanks
Happy scavenger bot user 
Noski

**Comment by Crypto2legit** [comment]
We plan on adding other strategies we have come up with. Thanks for the input.

**Comment by Crypto2legit** [comment]
With our API you could use webhook with script from TV
