### ISSUE TITLE
Use the power of comunity!

### ISSUE THREAD

**Issue by denisakov** [ScavengerBot/ScavengerBot#31]
Hi guys, I came here thinking that the suggestions are actually discussed and you are supporting meaningful conversations with legitimate parties.

Just consider that people who has account on GitHub are most likely developers (like my self) and you can actually talk code.

I'd be happy to help defining more complex strategies for risk management, stop-losses and trailing profit. However, I would also be glad to help with the code, if I can.

I got liquidated after 4 days. Lost $500. I'm not bitter, I like the idea, but it is clear that you guys are short-handed.

**Comment by Crypto2legit** [comment]
Thank you for your time. This is a community project and any and all help is appreciated. Can you send me a message in discord and we can talk further? Thanks again for you support.
