### ISSUE TITLE
API for "TURN ON" "TURN OFF" bots based on my own safety rules.

### ISSUE THREAD

**Issue by steta500** [ScavengerBot/ScavengerBot#33]
jo! is there a API where I could turn on/off bots based on my rules?
i would also be willing to develop this...its a mess without propper risk management, so, I am trading fulltime and have multiple safeties in place, so if one get´s triggered at 4am in the morning, I will not jump out of bed and turn on or off the bots...

that would be a HUGE help with very little effort, please let me know your thoughts SCAVENGER TEAM. I am willing to help if you let me.

 I am just thinking that a API that could turn on and off the bots would benefit the ENTIRE community, let me know your thoughts about this.

**Comment by Crypto2legit** [comment]
I am passing this onto the development team thank you for your input!
