### ISSUE TITLE
Liquidation risk notification

### ISSUE THREAD

**Issue by skyeshadow** [ScavengerBot/ScavengerBot#36]
Hello,

I'd like to see a feature from the app platform that would notify you when your liquid price came within a certain percentage of your mark price so that less checking was needed when DCA'ing out of large positions and you could take appropriate action if you came within that percent be it 10,20 or 30% not sure what would be a good warning point?

marpme01/06/2020
Well best notification alerts would be for all kinds of final orders aka:

* Stop loss triggered
* Position Profited

Also interesting would be if the bot would notify you about:

* Enable/Disable (also maintenance?)
* Payment Due
* Reaching Limits like: max position sizes, liquidation levels etc

https://github.com/ScavengerBot/ScavengerBot/issues/28

https://github.com/ScavengerBot/ScavengerBot/projects/1#card-31834735

https://github.com/ScavengerBot/ScavengerBot/projects/1#card-31834769

**Comment by Crypto2legit** [comment]
So you want a notification in the UI or email?

**Comment by Crypto2legit** [comment]
Thank you for the request it is being added to our community request area.

**Comment by Crypto2legit** [comment]
https://github.com/ScavengerBot/ScavengerBot/projects/1#card-31830817
