### ISSUE TITLE
Improvement suggestion: Set liq price range target

### ISSUE THREAD

**Issue by ebojali** [ScavengerBot/ScavengerBot#37]
For my bot, liq price was on 4400$  and price did get up to 4243$.
Today the only option is to be on your toes and shut down the bot in order to stop it from buying more.
I would like a protection mechanism for that, as follows: 
Configurable parameter in BOT UI where I don't want the liq price to move any closer that lets say 1500$ from my entry price...
If liq price moves to 1500$ from the entry price == stop buying :)

**Comment by Crypto2legit** [comment]
Version 2 now has setting for max balance and stop loss.
