### ISSUE TITLE
Watching and re-managing TP point only.

### ISSUE THREAD

**Issue by monthonparadise** [ScavengerBot/ScavengerBot#39]
Hi DEV
From my experiences, I usually let the bot trade and I manual trade also.
When bitcoin have a trending, I usually stop the bot, and place order manually order.
The problem is I have to watching its price, and set a new take profit point manual also.

So, I request watching mode, in this mode the bot will manage order, such as I place some limit order and price reached my order, let the bot change a new TP point automatically while I am busy, and this mode the bot **must not** open more orders, just watching and re-positioning TP points.

this feature can help me sleep well, thank you.

**Comment by Crypto2legit** [comment]
Yeah we have been speaking on this topic and are planning to work on this type of operation. We also have plans for when we submit and order manually or by automation the bot takes over.
