### ISSUE TITLE
Different balances

### ISSUE THREAD

**Issue by amosdeluniverso** [ScavengerBot/ScavengerBot#4]
Hi, not sure if this is a bug, but, in my bitmex account i have a balance of 0.0504, but the bot is showing a balance of 0.0550.
It is a new bot, it showed this difference right after verification.

**Comment by smoochy** [comment]
On the website the balance and PnL only updates once a day for now. As long as you see the balance on Bitmex, all is fine and the Bot is taking this into account. For later this month more detailed statistics are planned. Check on the [Roadmap](https://www.scavengerbot.io/#roadmap)
