### ISSUE TITLE
Stop Loss Customization

### ISSUE THREAD

**Issue by zhelfer0306** [ScavengerBot/ScavengerBot#46]
It would be great to have some more options with stop losses than a fixed trailing stop.

For instance, I would like to set a fixed stop x contracts away from each entry I make, creating a stop gradient. 

Right now, you have to exit your entire position with one stop. 

Thanks!

- Zack

**Comment by Sceat** [comment]
Would be nice to set stop loss with a specific % below entry and same for the take profit

**Comment by bigcountry-scav** [comment]
% has been added and gradient could be done through webhook in new release
