### ISSUE TITLE
Credit Amount in UI Incorrect

### ISSUE THREAD

**Issue by bigcountry-scav** [ScavengerBot/ScavengerBot#66]
1.) Prepay needs adjusted to be inline with USD
2.) Credit calculation still using BTC
3.) Invoice and Credits looking at the incorrect value that may or may not exist.

**Comment by oneezy** [comment]
Ok, @bigcountry-scav will take a look at this

**Comment by bigcountry-scav** [comment]
Fixed 3.0.43
