### ISSUE TITLE
Balance 0 despite > 0.05 in Bybit Wallet and API connected

### ISSUE THREAD

**Issue by manzanarre** [ScavengerBot/ScavengerBot#69]
Hi there
my account in Scavenger shows 0 Balance, bot is connected and the API permission is "Active Order and Positions"

Best
Lorenzo

**Comment by oneezy** [comment]
Have you started your bot yet? It will show a $0.00 balance until you start your bot. We plan on making this more clear in the future

**Comment by manzanarre** [comment]
![Bybit Balance](https://user-images.githubusercontent.com/77841287/107846068-0e4e1700-6de1-11eb-906d-10a7a70a1614.png)
![Scavengerbot 0 Balance](https://user-images.githubusercontent.com/77841287/107846069-0ee6ad80-6de1-11eb-8fc7-2040a9bbc9ea.png)

Thank you for your answer.
Yed I did, but also the dashboard shows[Image]

0

Get Outlook for Android<https://aka.ms/ghei36>

[Image]

________________________________

**Comment by manzanarre** [comment]
there must be something wit the APIs cause I opened another account and connected it and still doesn't work. I think I did everything correct otherwise the bot would have noticed that the connection was not possible... No more ideas...

**Comment by manzanarre** [comment]
I think I know what it was... I was focused on the Balance in the Dashboard but the Problem must have been with the Pai, I hold BTC and the pair I choose was BTCUSDT, now I switched to BTCUSD and it seems working

**Comment by oneezy** [comment]
Ahh good to hear that you got it resolved! I'm going to go ahead and close this issue, but if you run into any more trouble the best way to get support is by opening a ticket in our **Discord** [#💁support-only](https://discord.com/channels/482309483058692096/482339114339926016) channel. 

To create a ticket use this syntax:
```
-ticket open (type your support issue)
```
