### ISSUE TITLE
Please add "Mode" Enhancement

### ISSUE THREAD

**Issue by dougsryan** [ScavengerBot/ScavengerBot#9]
Scavenger Bot is a great tool, BUT , it's missing something basic for all users

Please add a "MODE" tool that lets a user select how "aggressive" Scavenger Bot does it's trading, the 3 selections are

-Normal (1x)
-Aggressive (2x)
-Very Aggressive (3x)

You guys know the tool best and what the settings should be for each of the 3 modes, above are only suggestions

Regards,

**Comment by smoochy** [comment]
Risk Management is already on the agenda and is planned to be released very soon. Have a look at the Roadmap on the website if you want to.

**Comment by Crypto2legit** [comment]
https://www.scavengerbot.io/#roadmap
